
import java.awt.Dimension;
import java.awt.Toolkit;


public class aboutUsScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public aboutUsScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        auTitlePanel = new javax.swing.JPanel();
        auTitle = new javax.swing.JLabel();
        auTitleBackground = new javax.swing.JLabel();
        jesterPic = new javax.swing.JLabel();
        jesterTitle = new javax.swing.JLabel();
        jesterPosition = new javax.swing.JLabel();
        richerPic = new javax.swing.JLabel();
        richerTitle = new javax.swing.JLabel();
        richerPosition = new javax.swing.JLabel();
        ronnelPic = new javax.swing.JLabel();
        ronnelTitle = new javax.swing.JLabel();
        ronnelPosition = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jesIntro = new javax.swing.JLabel();
        jesIntroBackground = new javax.swing.JLabel();
        richerIntro = new javax.swing.JLabel();
        richerIntroBackground = new javax.swing.JLabel();
        ronnelIntro = new javax.swing.JLabel();
        ronnelIntroBackground = new javax.swing.JLabel();
        aboutTitle = new javax.swing.JLabel();
        auGradientBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        auTitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        auTitle.setFont(new java.awt.Font("Gloss And Bloom", 0, 27)); // NOI18N
        auTitle.setForeground(new java.awt.Color(255, 255, 51));
        auTitle.setText("About Us");
        auTitlePanel.add(auTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 50));

        auTitleBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\feather.jpg")); // NOI18N
        auTitleBackground.setText("jLabel2");
        auTitlePanel.add(auTitleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, 50));

        jPanel1.add(auTitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 810, 50));

        jesterPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\superfinaljes.png")); // NOI18N
        jPanel1.add(jesterPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 250, 150));

        jesterTitle.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 26)); // NOI18N
        jesterTitle.setForeground(new java.awt.Color(0, 51, 51));
        jesterTitle.setText("Jester Miñon");
        jPanel1.add(jesterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 150, 40));

        jesterPosition.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 14)); // NOI18N
        jesterPosition.setForeground(new java.awt.Color(0, 51, 51));
        jesterPosition.setText("Chief Designer/Head Programmer");
        jPanel1.add(jesterPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 210, -1));

        richerPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\rsrsrsrsr.png")); // NOI18N
        jPanel1.add(richerPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 210, 170, 140));

        richerTitle.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 26)); // NOI18N
        richerTitle.setForeground(new java.awt.Color(0, 51, 51));
        richerTitle.setText(" Richer Waje");
        jPanel1.add(richerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 40));

        richerPosition.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 14)); // NOI18N
        richerPosition.setText("Senior Programmer/Creative Director");
        jPanel1.add(richerPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 240, -1));

        ronnelPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\lastonel.png")); // NOI18N
        jPanel1.add(ronnelPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 130, 170));

        ronnelTitle.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 24)); // NOI18N
        ronnelTitle.setForeground(new java.awt.Color(0, 51, 51));
        ronnelTitle.setText("Ronnel Palenzuela");
        jPanel1.add(ronnelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        ronnelPosition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ronnelPosition.setForeground(new java.awt.Color(0, 51, 51));
        ronnelPosition.setText("Junior Programmer/Concept Designer");
        jPanel1.add(ronnelPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 240, 40));

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jesIntro.setFont(new java.awt.Font("WeblySleek UI Light", 2, 15)); // NOI18N
        jesIntro.setText("A musician with a passion for coding. He ate chords for breakfast. ");
        jPanel1.add(jesIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jesIntroBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\grad 1.png")); // NOI18N
        jPanel1.add(jesIntroBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 104, 480, 40));

        richerIntro.setFont(new java.awt.Font("WeblySleek UI Light", 2, 15)); // NOI18N
        richerIntro.setText("An artist at heart and loves to meddle with ones and zeros.");
        jPanel1.add(richerIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 370, 20));

        richerIntroBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\grad 2.jpg")); // NOI18N
        richerIntroBackground.setText("jLabel1");
        jPanel1.add(richerIntroBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 470, 40));

        ronnelIntro.setFont(new java.awt.Font("WeblySleek UI Light", 2, 15)); // NOI18N
        ronnelIntro.setText("He writes spoken word poetry pieces and also create poetic source codes.");
        jPanel1.add(ronnelIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 460, 20));

        ronnelIntroBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\grad 3.png")); // NOI18N
        jPanel1.add(ronnelIntroBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 510, 40));

        aboutTitle.setFont(new java.awt.Font("WeblySleek UI Semilight", 0, 18)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(0, 51, 51));
        aboutTitle.setText("Developers:");
        jPanel1.add(aboutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        auGradientBackground.setForeground(new java.awt.Color(0, 51, 51));
        auGradientBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        auGradientBackground.setText("jLabel1");
        jPanel1.add(auGradientBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       this.hide();
       welcomeScreen ws = new welcomeScreen();
       ws.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel auGradientBackground;
    private javax.swing.JLabel auTitle;
    private javax.swing.JLabel auTitleBackground;
    private javax.swing.JPanel auTitlePanel;
    public javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jesIntro;
    private javax.swing.JLabel jesIntroBackground;
    private javax.swing.JLabel jesterPic;
    private javax.swing.JLabel jesterPosition;
    private javax.swing.JLabel jesterTitle;
    private javax.swing.JLabel richerIntro;
    private javax.swing.JLabel richerIntroBackground;
    private javax.swing.JLabel richerPic;
    private javax.swing.JLabel richerPosition;
    private javax.swing.JLabel richerTitle;
    private javax.swing.JLabel ronnelIntro;
    private javax.swing.JLabel ronnelIntroBackground;
    private javax.swing.JLabel ronnelPic;
    private javax.swing.JLabel ronnelPosition;
    private javax.swing.JLabel ronnelTitle;
    // End of variables declaration//GEN-END:variables
}
