
import java.awt.Dimension;
import java.awt.Toolkit;
import java.nio.charset.Charset;
import java.util.Random;
import javax.swing.JOptionPane;


public class bookInfo extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public bookInfo() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        errormessage = new javax.swing.JLabel();
        classbox = new javax.swing.JComboBox<>();
        departurebox = new javax.swing.JComboBox<>();
        destinationbox = new javax.swing.JComboBox<>();
        printButton = new javax.swing.JButton();
        destinationtext = new javax.swing.JLabel();
        departuretext = new javax.swing.JLabel();
        seattext = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        titleText = new javax.swing.JLabel();
        backhelpButton = new javax.swing.JButton();
        nametextarea = new javax.swing.JTextField();
        gradientBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(647, 484));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(647, 484));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errormessage.setFont(new java.awt.Font("WeblySleek UI Light", 1, 11)); // NOI18N
        errormessage.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(errormessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 220, -1));

        classbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "Economy", "Tourist" }));
        classbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classboxActionPerformed(evt);
            }
        });
        jPanel1.add(classbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 90, -1));

        departurebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bandar Seri Begawan", "Bangkok", "Dili", "Hanoi", "Jakarta", "Kuala Lumpur", "Manila", "Naypyidaw", "Phnom Penh", "Singapore City", "Vientiane",}));
        departurebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureboxActionPerformed(evt);
            }
        });
        jPanel1.add(departurebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, -1));

        destinationbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brunei", "Cambodia", "East Timor", "Indonesia", "Laos", "Malaysia", "Myanmar", "Philippines", "Singapore", "Thailand", "Vietnam" }));
        jPanel1.add(destinationbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 120, -1));

        printButton.setFont(new java.awt.Font("WeblySleek UI Light", 1, 18)); // NOI18N
        printButton.setText("Print Ticket");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel1.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 170, 100));

        destinationtext.setFont(new java.awt.Font("WeblySleek UI Light", 0, 18)); // NOI18N
        destinationtext.setForeground(new java.awt.Color(255, 255, 255));
        destinationtext.setText("Destination");
        jPanel1.add(destinationtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 90, -1));

        departuretext.setFont(new java.awt.Font("WeblySleek UI Light", 0, 18)); // NOI18N
        departuretext.setForeground(new java.awt.Color(255, 255, 255));
        departuretext.setText("Departure City");
        jPanel1.add(departuretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 110, -1));

        seattext.setFont(new java.awt.Font("WeblySleek UI Light", 0, 18)); // NOI18N
        seattext.setForeground(new java.awt.Color(255, 255, 255));
        seattext.setText("Seat Class");
        jPanel1.add(seattext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 90, -1));

        nameText.setFont(new java.awt.Font("WeblySleek UI Light", 0, 18)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setText("Passenger Name");
        jPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, -1));

        titleText.setFont(new java.awt.Font("Gloss And Bloom", 0, 24)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 51));
        titleText.setText(" Ticket Printer");
        jPanel1.add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 180, 40));

        backhelpButton.setBackground(new java.awt.Color(0, 153, 153));
        backhelpButton.setText("Cancel");
        backhelpButton.setBorder(null);
        backhelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backhelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        nametextarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextareaActionPerformed(evt);
            }
        });
        jPanel1.add(nametextarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 220, 30));

        gradientBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        gradientBackground.setText("jLabel1");
        jPanel1.add(gradientBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 0, 1010, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backhelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhelpButtonActionPerformed
        this.hide();
        mainProgScreen hs = new mainProgScreen();
        hs.setVisible(true);
                
    }//GEN-LAST:event_backhelpButtonActionPerformed

    private void nametextareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextareaActionPerformed
       try { 
        if (nametextarea.toString().trim().isEmpty()) {
            throw new IllegalArgumentException("Please enter a name.");
        }
       } catch (IllegalArgumentException e){
           
       }
    }//GEN-LAST:event_nametextareaActionPerformed

    private void classboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classboxActionPerformed

    private void departureboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureboxActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
                  
        String name = nametextarea.getText();
        String dep = departurebox.getSelectedItem().toString();
        String cbox = classbox.getSelectedItem().toString();
        String desti = destinationbox.getSelectedItem().toString();
        
        byte rand[] = new byte[7];
        new Random().nextBytes(rand);
        String flightno = new String(rand, Charset.forName("UTF-8"));
        
        if (nametextarea.getText().trim().isEmpty()) {
            errormessage.setText("Passenger Name must not be empty!");
        } 
             
        else {
        this.setVisible(false);
        new ticketClass(name,dep,cbox,desti,flightno).setVisible(true);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backhelpButton;
    public javax.swing.JComboBox<String> classbox;
    public javax.swing.JComboBox<String> departurebox;
    private javax.swing.JLabel departuretext;
    public javax.swing.JComboBox<String> destinationbox;
    private javax.swing.JLabel destinationtext;
    private javax.swing.JLabel errormessage;
    private javax.swing.JLabel gradientBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameText;
    public javax.swing.JTextField nametextarea;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel seattext;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
