
import java.awt.Dimension;
import java.awt.Toolkit;


public class helpScreen extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public helpScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mpTitlePanel = new javax.swing.JPanel();
        mpTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backgroundPhoto = new javax.swing.JLabel();
        backhelpButton = new javax.swing.JButton();
        flavorText1 = new javax.swing.JLabel();
        flavorText2 = new javax.swing.JLabel();
        instructSeparator = new javax.swing.JSeparator();
        instructText1 = new javax.swing.JLabel();
        instructText2 = new javax.swing.JLabel();
        instructText3 = new javax.swing.JLabel();
        footerText = new javax.swing.JLabel();
        footerText2 = new javax.swing.JLabel();
        instruct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mpTitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mpTitle.setFont(new java.awt.Font("Gloss And Bloom", 0, 27)); // NOI18N
        mpTitle.setForeground(new java.awt.Color(255, 255, 51));
        mpTitle.setText("Instructions");
        mpTitlePanel.add(mpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\feather.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        mpTitlePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, 50));

        jPanel1.add(mpTitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 810, 50));

        backgroundPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\thinker-28741_640.png")); // NOI18N
        jPanel1.add(backgroundPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 580, 660));

        backhelpButton.setBackground(new java.awt.Color(0, 153, 153));
        backhelpButton.setText("Back");
        backhelpButton.setBorder(null);
        backhelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backhelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        flavorText1.setFont(new java.awt.Font("WeblySleek UI Light", 0, 15)); // NOI18N
        flavorText1.setForeground(new java.awt.Color(204, 204, 204));
        flavorText1.setText("SEAstory's main goal is to improve the students' historical knowledge");
        jPanel1.add(flavorText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 460, 20));

        flavorText2.setFont(new java.awt.Font("WeblySleek UI Light", 0, 15)); // NOI18N
        flavorText2.setForeground(new java.awt.Color(204, 204, 204));
        flavorText2.setText("of the Southeast Asian culture.");
        jPanel1.add(flavorText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 420, -1));
        jPanel1.add(instructSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 420, 10));

        instructText1.setFont(new java.awt.Font("WeblySleek UI Light", 0, 15)); // NOI18N
        instructText1.setForeground(new java.awt.Color(204, 204, 204));
        instructText1.setText("Just click on your desired Southeast Asian nation, then choose ");
        jPanel1.add(instructText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 420, -1));

        instructText2.setFont(new java.awt.Font("WeblySleek UI Light", 0, 15)); // NOI18N
        instructText2.setForeground(new java.awt.Color(204, 204, 204));
        instructText2.setText("the person's body part, then a corresponding historical data");
        jPanel1.add(instructText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 420, -1));

        instructText3.setFont(new java.awt.Font("WeblySleek UI Light", 0, 15)); // NOI18N
        instructText3.setForeground(new java.awt.Color(204, 204, 204));
        instructText3.setText("will be shown. Enjoy!");
        jPanel1.add(instructText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        footerText.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        footerText.setText("Made by the Nation University Information Technology Students");
        jPanel1.add(footerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, 20));

        footerText2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        footerText2.setText("with guidance of Prof. Joseph Marvin Imperial. Copyright 2019. All Rights Reserved. ");
        jPanel1.add(footerText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 20));

        instruct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        instruct.setText("jLabel1");
        jPanel1.add(instruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 760, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backhelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhelpButtonActionPerformed
        this.hide();
        welcomeScreen ws = new welcomeScreen();
        ws.setVisible(true);
    }//GEN-LAST:event_backhelpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPhoto;
    private javax.swing.JButton backhelpButton;
    private javax.swing.JLabel flavorText1;
    private javax.swing.JLabel flavorText2;
    private javax.swing.JLabel footerText;
    private javax.swing.JLabel footerText2;
    private javax.swing.JLabel instruct;
    private javax.swing.JSeparator instructSeparator;
    private javax.swing.JLabel instructText1;
    private javax.swing.JLabel instructText2;
    private javax.swing.JLabel instructText3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mpTitle;
    private javax.swing.JPanel mpTitlePanel;
    // End of variables declaration//GEN-END:variables
}
