
import java.awt.Dimension;
import java.awt.Toolkit;


public class indonav extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public indonav() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lefteye = new javax.swing.JButton();
        righteye = new javax.swing.JButton();
        leftear = new javax.swing.JButton();
        rightear = new javax.swing.JButton();
        mouth = new javax.swing.JButton();
        lefthand = new javax.swing.JButton();
        righthand = new javax.swing.JButton();
        foot = new javax.swing.JButton();
        indonesian = new javax.swing.JLabel();
        backhelpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        flavtext = new javax.swing.JLabel();
        flavtext2 = new javax.swing.JLabel();
        flavtext3 = new javax.swing.JLabel();
        indomap = new javax.swing.JLabel();
        gradbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lefteye.setOpaque(false);
        lefteye.setContentAreaFilled(false);
        lefteye.setBorderPainted(false);
        lefteye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lefteyeActionPerformed(evt);
            }
        });
        jPanel1.add(lefteye, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 20, 30));

        righteye.setOpaque(false);
        righteye.setContentAreaFilled(false);
        righteye.setBorderPainted(false);
        righteye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                righteyeActionPerformed(evt);
            }
        });
        jPanel1.add(righteye, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 20, 30));

        leftear.setOpaque(false);
        leftear.setContentAreaFilled(false);
        leftear.setBorderPainted(false);
        leftear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftearActionPerformed(evt);
            }
        });
        jPanel1.add(leftear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 40, 40));

        rightear.setOpaque(false);
        rightear.setContentAreaFilled(false);
        rightear.setBorderPainted(false);
        rightear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightearActionPerformed(evt);
            }
        });
        jPanel1.add(rightear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, 40));

        mouth.setOpaque(false);
        mouth.setContentAreaFilled(false);
        mouth.setBorderPainted(false);
        mouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouthActionPerformed(evt);
            }
        });
        jPanel1.add(mouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 30, 40));

        lefthand.setOpaque(false);
        lefthand.setContentAreaFilled(false);
        lefthand.setBorderPainted(false);
        jPanel1.add(lefthand, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 50, 60));

        righthand.setOpaque(false);
        righthand.setContentAreaFilled(false);
        righthand.setBorderPainted(false);
        jPanel1.add(righthand, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 50, 60));

        foot.setOpaque(false);
        foot.setContentAreaFilled(false);
        foot.setBorderPainted(false);
        jPanel1.add(foot, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 90, 40));

        indonesian.setIcon(new javax.swing.ImageIcon("D:\\A System Photo Source\\indonesia resized.png")); // NOI18N
        jPanel1.add(indonesian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 250, 460));

        backhelpButton.setBackground(new java.awt.Color(0, 153, 153));
        backhelpButton.setText("Back");
        backhelpButton.setBorder(null);
        backhelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backhelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 20));

        jLabel1.setFont(new java.awt.Font("Gloss And Bloom", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText(" Indonesia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, 50));

        flavtext.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext.setText("Click my eyes, ears");
        jPanel1.add(flavtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 150, 20));

        flavtext2.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext2.setText("mouth, hands");
        jPanel1.add(flavtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, 20));

        flavtext3.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext3.setText("and foot!");
        jPanel1.add(flavtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        indomap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\resources\\SEAstory Photos\\borders-2099206_640.png")); // NOI18N
        jPanel1.add(indomap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 620, 350));

        gradbackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        gradbackground.setText("jLabel1");
        jPanel1.add(gradbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backhelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhelpButtonActionPerformed
        this.hide();
        mainProgScreen mps = new mainProgScreen();
        mps.setVisible(true);
    }//GEN-LAST:event_backhelpButtonActionPerformed

    private void righteyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_righteyeActionPerformed
        this.hide();
        indoeyenav ie = new indoeyenav();
        ie.setVisible(true);
    }//GEN-LAST:event_righteyeActionPerformed

    private void lefteyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lefteyeActionPerformed
        this.hide();
        indoeyenav ie = new indoeyenav();
        ie.setVisible(true);
    }//GEN-LAST:event_lefteyeActionPerformed

    private void mouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouthActionPerformed
        this.hide();
        indomouthnav im = new indomouthnav();
        im.setVisible(true);
    }//GEN-LAST:event_mouthActionPerformed

    private void leftearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftearActionPerformed
        this.hide();
        indoearnav in = new indoearnav();
        in.setVisible(true);
    }//GEN-LAST:event_leftearActionPerformed

    private void rightearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightearActionPerformed
        this.hide();
        indoearnav in = new indoearnav();
        in.setVisible(true);
    }//GEN-LAST:event_rightearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backhelpButton;
    private javax.swing.JLabel flavtext;
    private javax.swing.JLabel flavtext2;
    private javax.swing.JLabel flavtext3;
    private javax.swing.JButton foot;
    private javax.swing.JLabel gradbackground;
    private javax.swing.JLabel indomap;
    private javax.swing.JLabel indonesian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leftear;
    private javax.swing.JButton lefteye;
    private javax.swing.JButton lefthand;
    private javax.swing.JButton mouth;
    private javax.swing.JButton rightear;
    private javax.swing.JButton righteye;
    private javax.swing.JButton righthand;
    // End of variables declaration//GEN-END:variables
}
