
import java.awt.Dimension;
import java.awt.Toolkit;


public class thainav extends javax.swing.JFrame {

    /**
     * Creates new form mainProgFrame
     */
    public thainav() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lefteye1 = new javax.swing.JButton();
        mouth1 = new javax.swing.JButton();
        righteye1 = new javax.swing.JButton();
        rightear1 = new javax.swing.JButton();
        leftear1 = new javax.swing.JButton();
        lefthand1 = new javax.swing.JButton();
        righthand1 = new javax.swing.JButton();
        rightfoot1 = new javax.swing.JButton();
        leftfoot1 = new javax.swing.JButton();
        flavtext = new javax.swing.JLabel();
        flavtext2 = new javax.swing.JLabel();
        flavtext3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        leftear = new javax.swing.JButton();
        lefteye = new javax.swing.JButton();
        mouth = new javax.swing.JButton();
        righteye = new javax.swing.JButton();
        rightear = new javax.swing.JButton();
        lefthand = new javax.swing.JButton();
        righthand = new javax.swing.JButton();
        leftfoot = new javax.swing.JButton();
        rightfoot = new javax.swing.JButton();
        thai = new javax.swing.JLabel();
        thaimap = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        instruct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lefteye1.setContentAreaFilled(false);
        lefteye1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lefteye1ActionPerformed(evt);
            }
        });
        jPanel1.add(lefteye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 30, 10));

        mouth1.setContentAreaFilled(false);
        mouth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouth1ActionPerformed(evt);
            }
        });
        jPanel1.add(mouth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 30, 20));

        righteye1.setContentAreaFilled(false);
        righteye1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                righteye1ActionPerformed(evt);
            }
        });
        jPanel1.add(righteye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 20));

        rightear1.setContentAreaFilled(false);
        rightear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightear1ActionPerformed(evt);
            }
        });
        jPanel1.add(rightear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 20, 30));

        leftear1.setContentAreaFilled(false);
        leftear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftear1ActionPerformed(evt);
            }
        });
        jPanel1.add(leftear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 20, 30));

        lefthand1.setContentAreaFilled(false);
        lefthand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lefthand1ActionPerformed(evt);
            }
        });
        jPanel1.add(lefthand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 50, 50));

        righthand1.setContentAreaFilled(false);
        righthand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                righthand1ActionPerformed(evt);
            }
        });
        jPanel1.add(righthand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, 50));

        rightfoot1.setContentAreaFilled(false);
        rightfoot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightfoot1ActionPerformed(evt);
            }
        });
        jPanel1.add(rightfoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 50, 60));

        leftfoot1.setContentAreaFilled(false);
        leftfoot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftfoot1ActionPerformed(evt);
            }
        });
        jPanel1.add(leftfoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 40, 50));

        flavtext.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext.setText("Click my eyes, ears");
        jPanel1.add(flavtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 20));

        flavtext2.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext2.setText("mouth, hands");
        jPanel1.add(flavtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, 20));

        flavtext3.setFont(new java.awt.Font("WeblySleek UI Light", 2, 18)); // NOI18N
        flavtext3.setText("and foot!");
        jPanel1.add(flavtext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gloss And Bloom", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText(" Thailand");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 130, 50));

        leftear.setContentAreaFilled(false);
        leftear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftearActionPerformed(evt);
            }
        });
        jPanel1.add(leftear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 20, 30));

        lefteye.setContentAreaFilled(false);
        lefteye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lefteyeActionPerformed(evt);
            }
        });
        jPanel1.add(lefteye, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 20, 20));

        mouth.setContentAreaFilled(false);
        mouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouthActionPerformed(evt);
            }
        });
        jPanel1.add(mouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 30, 30));

        righteye.setContentAreaFilled(false);
        righteye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                righteyeActionPerformed(evt);
            }
        });
        jPanel1.add(righteye, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 20, 10));

        rightear.setContentAreaFilled(false);
        rightear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightearActionPerformed(evt);
            }
        });
        jPanel1.add(rightear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 20, 30));

        lefthand.setContentAreaFilled(false);
        lefthand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lefthandActionPerformed(evt);
            }
        });
        jPanel1.add(lefthand, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 40, 40));

        righthand.setContentAreaFilled(false);
        righthand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                righthandActionPerformed(evt);
            }
        });
        jPanel1.add(righthand, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 40, 40));

        leftfoot.setContentAreaFilled(false);
        leftfoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftfootActionPerformed(evt);
            }
        });
        jPanel1.add(leftfoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 60, 50));

        rightfoot.setContentAreaFilled(false);
        rightfoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightfootActionPerformed(evt);
            }
        });
        jPanel1.add(rightfoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 60, 50));

        thai.setIcon(new javax.swing.ImageIcon("D:\\A System Photo Source\\updated na tao\\thailand resized.png")); // NOI18N
        jPanel1.add(thai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 450, 520));

        thaimap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Documents\\NetBeansProjects\\AccuFact\\src\\photos and other resource\\thailand map resized final.png")); // NOI18N
        jPanel1.add(thaimap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -20, 660, 620));

        backbutton.setBackground(new java.awt.Color(0, 153, 153));
        backbutton.setText("Back");
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        instruct.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        instruct.setText("jLabel1");
        jPanel1.add(instruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 670, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        this.hide();
        mainProgScreen mps = new mainProgScreen();
        mps.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void leftearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftearActionPerformed
        this.setVisible(false);
        new thaiearnav().setVisible(true);
    }//GEN-LAST:event_leftearActionPerformed

    private void lefteyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lefteyeActionPerformed
        this.setVisible(false);
        new thaieyenav().setVisible(true);
    }//GEN-LAST:event_lefteyeActionPerformed

    private void mouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouthActionPerformed
        this.setVisible(true);
        new thaimouthnav().setVisible(true);
    }//GEN-LAST:event_mouthActionPerformed

    private void righteyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_righteyeActionPerformed
        this.setVisible(false);
        new thaieyenav().setVisible(true);
    }//GEN-LAST:event_righteyeActionPerformed

    private void rightearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightearActionPerformed
        this.setVisible(false);
        new thaiearnav().setVisible(true);
    }//GEN-LAST:event_rightearActionPerformed

    private void lefthandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lefthandActionPerformed
        this.setVisible(false);
        new thaihandnav().setVisible(true);
    }//GEN-LAST:event_lefthandActionPerformed

    private void righthandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_righthandActionPerformed
        this.setVisible(false);
        new thaihandnav().setVisible(true);
    }//GEN-LAST:event_righthandActionPerformed

    private void leftfootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftfootActionPerformed
        this.setVisible(true);
        new thaifootnav().setVisible(true);
    }//GEN-LAST:event_leftfootActionPerformed

    private void rightfootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightfootActionPerformed
        this.setVisible(false);
        new thaifootnav().setVisible(true);
    }//GEN-LAST:event_rightfootActionPerformed

    private void lefteye1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lefteye1ActionPerformed
        this.setVisible(false);
        new vieteyenav().setVisible(true);
    }//GEN-LAST:event_lefteye1ActionPerformed

    private void mouth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouth1ActionPerformed
        this.setVisible(true);
        new vietmouthnav().setVisible(true);
    }//GEN-LAST:event_mouth1ActionPerformed

    private void righteye1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_righteye1ActionPerformed
        this.setVisible(false);
        new vieteyenav().setVisible(true);
    }//GEN-LAST:event_righteye1ActionPerformed

    private void rightear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightear1ActionPerformed
        this.setVisible(false);
        new vietearnav().setVisible(true);
    }//GEN-LAST:event_rightear1ActionPerformed

    private void leftear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftear1ActionPerformed
        this.setVisible(false);
        new vietearnav().setVisible(true);
    }//GEN-LAST:event_leftear1ActionPerformed

    private void lefthand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lefthand1ActionPerformed
        this.setVisible(false);
        new viethandnav().setVisible(true);
    }//GEN-LAST:event_lefthand1ActionPerformed

    private void righthand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_righthand1ActionPerformed
        this.setVisible(false);
        new viethandnav().setVisible(true);
    }//GEN-LAST:event_righthand1ActionPerformed

    private void rightfoot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightfoot1ActionPerformed
        this.setVisible(false);
        new vietfootnav().setVisible(true);
    }//GEN-LAST:event_rightfoot1ActionPerformed

    private void leftfoot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftfoot1ActionPerformed
        this.setVisible(true);
        new vietfootnav().setVisible(true);
    }//GEN-LAST:event_leftfoot1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel flavtext;
    private javax.swing.JLabel flavtext2;
    private javax.swing.JLabel flavtext3;
    private javax.swing.JLabel instruct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton leftear;
    private javax.swing.JButton leftear1;
    private javax.swing.JButton lefteye;
    private javax.swing.JButton lefteye1;
    private javax.swing.JButton leftfoot;
    private javax.swing.JButton leftfoot1;
    private javax.swing.JButton lefthand;
    private javax.swing.JButton lefthand1;
    private javax.swing.JButton mouth;
    private javax.swing.JButton mouth1;
    private javax.swing.JButton rightear;
    private javax.swing.JButton rightear1;
    private javax.swing.JButton righteye;
    private javax.swing.JButton righteye1;
    private javax.swing.JButton rightfoot;
    private javax.swing.JButton rightfoot1;
    private javax.swing.JButton righthand;
    private javax.swing.JButton righthand1;
    private javax.swing.JLabel thai;
    private javax.swing.JLabel thaimap;
    // End of variables declaration//GEN-END:variables
}
