import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;


public class welcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form welcomeScreen
     */
    public welcomeScreen() {
        initComponents();
        // CENTERING
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        aboutusButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        philippines = new javax.swing.JLabel();
        versionInfo = new javax.swing.JLabel();
        secondpanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEAstory - an offline history and culture directory of SEA Nations");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPanel.setBackground(new java.awt.Color(0, 51, 51));
        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setFont(new Font("Tahoma", Font.PLAIN, 12));
        exitButton.setFocusPainted(false);
        exitButton.setBackground(new java.awt.Color(0, 153, 153));
        exitButton.setFont(new java.awt.Font("WeblySleek UI Light", 1, 20)); // NOI18N
        exitButton.setText("QUIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 160, 60));

        helpButton.setFont(new Font("Tahoma", Font.PLAIN, 12));
        helpButton.setFocusPainted(false);
        helpButton.setBackground(new java.awt.Color(0, 153, 153));
        helpButton.setFont(new java.awt.Font("WeblySleek UI Light", 1, 11)); // NOI18N
        helpButton.setText("Help");
        helpButton.setMaximumSize(new java.awt.Dimension(77, 23));
        helpButton.setMinimumSize(new java.awt.Dimension(77, 23));
        helpButton.setPreferredSize(new java.awt.Dimension(77, 23));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 90, 20));

        startButton.setFont(new Font("Tahoma", Font.PLAIN, 12));
        startButton.setFocusPainted(false);
        startButton.setBackground(new java.awt.Color(0, 153, 153));
        startButton.setFont(new java.awt.Font("WeblySleek UI Light", 1, 20)); // NOI18N
        startButton.setText("EXPLORE");
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startButton.setFocusPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 60));

        aboutusButton.setFont(new Font("Tahoma", Font.PLAIN, 12));
        aboutusButton.setFocusPainted(false);
        aboutusButton.setBackground(new java.awt.Color(0, 153, 153));
        aboutusButton.setFont(new java.awt.Font("WeblySleek UI Light", 1, 11)); // NOI18N
        aboutusButton.setText("About Us");
        aboutusButton.setToolTipText("Want to know more about us? Click here!");
        aboutusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(aboutusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 90, 20));

        jPanel1.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 419, 730, 90));

        jLabel1.setFont(new java.awt.Font("WeblySleek UI Light", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Southeast Asian Nations' History");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 210, -1));

        mainTitle.setFont(new java.awt.Font("Gloss And Bloom", 0, 80)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 51));
        mainTitle.setText("SEAstory");
        jPanel1.add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 370, 240));

        philippines.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\resources\\SEAstory Photos\\borders-2099222_640.png")); // NOI18N
        jPanel1.add(philippines, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 490, 480));

        versionInfo.setFont(new java.awt.Font("WeblySleek UI Semilight", 2, 12)); // NOI18N
        versionInfo.setText("ver. 1.0.0");
        jPanel1.add(versionInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 70, 40));

        secondpanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palenzuela\\Desktop\\GUI Photo Source\\Gradient-Free-Blurry-Abstract-Background-Photos.png")); // NOI18N
        jPanel1.add(secondpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusButtonActionPerformed
        this.hide();
        aboutUsScreen aus = new aboutUsScreen();      
        aus.setVisible(true);
        
    }//GEN-LAST:event_aboutusButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        this.hide();
        mainProgScreen main = new mainProgScreen();
        main.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        this.hide();
        helpScreen hs = new helpScreen();
        hs.setVisible(true);
    }//GEN-LAST:event_helpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new welcomeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aboutusButton;
    public javax.swing.JPanel buttonPanel;
    public javax.swing.JButton exitButton;
    public javax.swing.JButton helpButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel mainTitle;
    public javax.swing.JLabel philippines;
    public javax.swing.JLabel secondpanel;
    public javax.swing.JButton startButton;
    public javax.swing.JLabel versionInfo;
    // End of variables declaration//GEN-END:variables
}

